### ISSUE TITLE
Python KeyError

### ISSUE THREAD

**Issue by smilernet** [debrigand/Solaredge-monitoring#1]
Hi,

I'm getting the error KeyError: 'e_day' -  all I've gone is clone & edit the file with my DB & inverter details:

Any ideas?

Here's the output after executing the python script:

Running at 2019-09-13 14:58:28.776453
Since last run we produced 22598.03 Wh
Traceback (most recent call last):
  File "fetch.py", line 161, in <module>
    save_data(db, inverter_data, optimizer_data, now)
  File "fetch.py", line 146, in save_data
    cursor.execute(sql2, (now, opt['serial'], opt['timestamp'], opt['u_out']*inv['i_dc'], opt['u_out'], opt['u_in'], opt['e_day'], opt['e_total'],opt['temp']))
KeyError: 'e_day'

**Comment by ghost** [comment]
You're right, the code doesn't work correctly when the database is empty. That should be fixed now by commit a15e678fd3d91b

**Comment by smilernet** [comment]
Awesome that has fixed it!

Data is now populating the MySQL database
